erica-likelion/fall-festival-client

src/assets/icons/left-arrow.svg
src/assets/icons/trash.svg
src/components/nav-bar/NavBar.tsx
src/main.tsx
src/pages/favorites/Favorites.styles.ts
src/pages/favorites/Favorites.tsx
src/pages/index.ts
src/router/AppRouter.tsx

- trash.svg 클릭 시 찜하기 목록 삭제 연동 
- 상단 nav바 아이콘 수정
- favorites 페이지 라우팅 연결
- favorites 스타일 페이지 작성
- 휴지통 버튼 클릭 -> 주점 목록 찜하기 목록 상태 반영

feat: 찜한 주점 목록 페이지 구현

---

src/assets/icons/close-black.svg
src/assets/icons/close-search.svg
src/assets/icons/search-gray.svg
src/pages/booth/Booth.tsx

- close-search.svg, search-gray.svg 등 검색창에 필요한 svg 추가
- 주점 상단바 search -> map/search 로 navigate 연결

feat: 주점 찜하기 목록 페이지 완성

---

vite.config.ts

fix: rollback vite config

---

src/layout/nav/Nav.styles.ts

fix: update background gradient color in Nav component

fix: update background gradient color in Nav component

---

src/pages/main/fortune/FortuneOnboarding.styles.ts
src/pages/main/fortune/FortuneResult.styles.ts
src/pages/main/fortune/FortuneSelecting.styles.ts
vite.config.ts

- 스크롤 제거
- 컴포넌트 gap 수정
- 사파리 내 카드 회전 기능 활성화

fix: 운세 페이지 환경 호환성 관련 수정 (test)

---

src/components/image-text-frame/ImageTextFrame.styles.ts

- pickup 버튼 css 값 수정 (고정값 -> max-content)

fix: pickup 버튼 width 값 수정

---

src/pages/main/fortune/FortuneOnboarding.styles.ts
src/pages/main/fortune/FortuneResult.styles.ts
src/styles/theme.ts

- ios 내 input 입력시 자동 확대 방지를 위한 폰트 크기 수정 (16px)
- placeholder 글자 투명도 추가
- 운세카드 테두리 효과 css: radius 수정

fix(fortune): 온보딩 placeholder 폰트 사이즈 수정 및 운세 카드 css 수정

---

src/components/toast/Toast.tsx

fix: remove unnecessary React import in Toast component

fix: remove unnecessary React import in Toast component

---

src/features/main/components/notice/MainNoticeList.styles.ts
src/features/main/components/notice/MainNoticeList.tsx
src/pages/main/notice/Notice.styles.ts
src/pages/main/notice/Notice.tsx
src/pages/main/notice/NoticeDetail.styles.ts
src/pages/main/notice/NoticeDetail.tsx
src/services/fortuneService.ts
src/services/index.ts
src/services/noticeService.ts

feat: implement notice API endpoint request
- 공지사항 조회 API 요청 구현

feat: implement notice API endpoint request

---

src/pages/map/MapPage.tsx
src/pages/map/SearchPage.tsx
src/pages/performance/Performance.styles.ts
src/pages/performance/Performance.tsx

공연, 지도 페이지 nav 바에 뒤로가기버튼, x버튼 제거해달라고 하셔서 제거했습니다.

refactor: 공연, 지도 페이지 뒤로가기버튼 x버튼 제거

---

src/features/main/components/notice/NoticeDetailCarousels.styles.ts
src/features/main/components/notice/NoticeDetailCarousels.tsx

feat: replace framer-motion with react-slick in NoticeDetailCarousels and add page indicator pill
- 공지사항 내용 조회 페이지 캐러셀 react-slick으로 구현
- 페이지 표시 Pill 컴포넌트 추가

feat: replace framer-motion with react-slick in NoticeDetailCarousels

---

src/services/boothService.ts

- 기존 api 내 fallback 구조 완전 제거 
- 에러 예외 처리 점검 (hook, ui)

fix: 주점 api 내 fallback 구조 완전 제거

---

src/pages/main/fortune/FortuneSelecting.styles.ts
src/pages/main/fortune/FortuneSelecting.tsx

- 운세 API 네트워크 에러시 토스트 알림 구현
- 운세 카드 효과 호환성 개선 
(모바일 터치 디바이스 대응 / GPU 가속 최적화 / Webkit 브라우저 호환성)
- 운세 선택 페이지 좌우 드래그 비활성화

feat: 운세 관련 오류 토스트 알림 출력 및 운세 카드 효과 호환성 개선

---

src/features/booth/components/BoothList.styles.ts

- tab 컨테이너 top margin 값 수정
- tabslider 너비, 높이 수정
- 활성화 버튼 box-shadow 추가
- boothlist 전체 컨테이너 top margin 값 음수로 수정

fix: 주점 목록 리스트 레이아웃 수정

---

src/features/booth/components/BoothList.styles.ts

fix: 주점 목록 gap 값 수정

---

src/features/main/components/carousels/EventCarousels.styles.ts
src/features/main/components/carousels/EventCarousels.tsx
src/features/main/components/notice/NoticeDetailCarousels.styles.ts

Feat main PR
- 메인 화면 페이지 Pill 위치 표시 오류 수정
- 공지 화면 이미지 max-height 설정

Feat main PR

---

src/features/main/components/carousels/EventCarousels.styles.ts
src/features/main/components/notice/NoticeDetailCarousels.styles.ts

fix: backdrop-filter not working issue
- backdrop-filter의 blur 효과가 작동하지 않는 이슈 해결

fix: backdrop-filter not working issue

---

src/components/tabs/Tabs.tsx
src/pages/main/notice/Notice.styles.ts
src/pages/main/notice/Notice.tsx

feat: add tabs at notice list page
공지사항 목록에 태그별 분류 Tab 컴포넌트 추가

feat: add tabs at notice list page

---

src/components/modal/Modal.style.ts
src/components/modal/Modal.tsx
src/components/tabs/Tabs.styles.ts
src/components/tabs/Tabs.tsx
src/features/performance/ModalHelp.styles.ts
src/features/performance/NewCarousel.styles.ts
src/pages/performance/Performance.styles.ts
src/pages/performance/Performance.tsx
src/pages/performance/PerformanceDetail.styles.ts
src/pages/performance/PerformanceDetail.tsx
src/services/artistService.ts
src/stores/usePerformanceStore.ts
src/types/artist.type.ts

- 공연 페이지 api zustand 이용해서 컴포넌트 마운트 시 한 번만 데이터 로드되게 해놨습니다

refactor: zustand로 api 전역 관리

---

src/features/performance/NewCarousel.styles.ts
src/pages/performance/Performance.styles.ts

fix: adjust VerticalLine height and add flex properties to Carousel
공연(/performance) 캐러셀 높이 viewport에 맞게 대응하도록 수정

fix: adjust VerticalLine height and add flex properties to Carousel

---

src/pages/polaroid/Polaroid.tsx

fix: update exit handler to show confirmation modal only for specific steps

fix: update exit handler to show confirmation modal only for specific steps

---

src/components/nav-bar/NavBar.styles.ts

fix: right section 하단 간격 수정

---

src/features/performance/NewCarousel.styles.ts
src/layout/nav/nav-item.tsx
src/pages/performance/PerformanceDetail.styles.ts

- 페이지 활성화 시 하단 버튼 사이즈 수정되는 부분 수정했습니다
- 아티스트 상세 페이지 디자인 깨지는 부분 해결했습니다

refactor: 페이지 활성화 시 하단 버튼 사이즈 수정

---

src/features/booth/components/MenuList.tsx
src/services/boothService.ts
src/types/booth.types.ts

- api 내 세트, 기타 항목이 없을 경우, 화면에서 해당 카테고리 제거
- api 필드 내 세트 분류 항목 추가

fix: 주점 카테고리 내 세트 항목 추가 및 카테고리 동적 조정

---

src/features/performance/NewCarousel.styles.ts
src/pages/performance/Performance.styles.ts

fix: add removed flex attribute of performance carousel
Performace 페이지 레이아웃 일부 수정

fix: add removed flex attribute of performance carousel

---

src/pages/polaroid/Polaroid.tsx

fix: conditionally render close button in NavBar based on current step
- 폴라로이드 온보딩 화면에서 closeBt 숨기기

fix: conditionally render close button in NavBar based on current step

---

index.html
vercel.json

fix: 캐시 주기 수정

---

src/constants/performance/SingerList.ts

refactor: 하츠투하트 -> 하츠투하츠로 변경

---

src/features/booth/components/MenuList.tsx

fix: 주점 메뉴 탭버튼 숨김 로직 수정

---

src/features/map/bottomsheet/BottomSheet.tsx
src/features/performance/NewCarousel.tsx
src/hooks/useKakaoMap.ts
src/pages/booth/BoothDetail.tsx
src/pages/map/MapPage.tsx
src/pages/performance/Performance.tsx
src/pages/performance/PerformanceDetail.tsx
src/services/artistService.ts
src/stores/useMarkerStore.ts
src/stores/usePerformanceStore.ts
src/utils/searchHistoryUtils.ts

- 00:00 ~ 16:59 / 17:00 ~ 23:59 시간 별로 푸드트럭 표시 영역 수정했습니다

refactor: 푸드트럭 시간 별 표시 영역 수정
